name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.22.2"
      - name: Install dependencies
        run: go get .
      - name: Build
        run: |
          mkdir build
          go build -o build/sync .
      - name: push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: data
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
