name: Go

on:
  workflow_dispatch:
  schedule: [{cron: "0/10 0 * * *"}]
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.22.2"
      - name: Install dependencies
        run: go get .
      - name: RUN
        run: go run .
      - name: Build
        run: |
          mkdir build
          mv live.json build
      - name: push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: data
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
