name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.2'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -o sync .
      - name: push to data branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add sync
          git commit -m "sync from main"
          git push origin data
